server:
  port: 8088

spring:
  application:
    name: api-gateway

# Eureka off
eureka:
  client:
    enabled: false

zuul:
  ignored-services: '*'
  
  # Pasar encabezados sensibles como Authorization si usas JWT (Va a nivel raíz de zuul)
  sensitive-headers: Cookie,Set-Cookie,Authorization
  
  # Definición manual de tus rutas (De la más específica a la más genérica)
  routes:
  routes:
    auth-service:
      path: /auth/**
      url: http://74.208.192.175:8089
      strip-prefix: false
      
    ordenes-service:
      path: /api/ordenes/**
      url: http://74.208.192.175:8082
      strip-prefix: false

    finanzas-service:
      path: /api/dashboard/**
      url: http://74.208.192.175:8082
      strip-prefix: false

    personas-service:
      path: /api/**
      url: http://74.208.192.175:8081
      strip-prefix: false