server:
  port: 8088

spring:
  application:
    name: api-gateway

# Eureka off
eureka:
  client:
    enabled: false

zuul:
  ignored-services: '*'
  # Add Authorization if needed
  sensitive-headers: Cookie,Set-Cookie
  
  routes:
    auth-service:
      path: /auth/**
      url: http://host.docker.internal:8089
      strip-prefix: false
      
    ordenes-service:
      path: /api/ordenes/**
      url: http://host.docker.internal:8082
      strip-prefix: false

    finanzas-service:
      path: /api/dashboard/**
      url: http://host.docker.internal:8082
      strip-prefix: false

    compras-service:
      path: /api/compras/**
      url: http://host.docker.internal:8082
      strip-prefix: false

    operaciones-service:
      path: /api/operaciones/**
      url: http://host.docker.internal:8082
      strip-prefix: false

    productos-service:
      path: /api/productos/**
      url: http://host.docker.internal:8082
      strip-prefix: false

    imagenes.service:
      path: /api/uploads/**
      url: http://host.docker.internal:8082
      strip-prefix: false

    personas-service:
      path: /api/**
      url: http://host.docker.internal:8081
      strip-prefix: false